title: Ahmed_Farahat_Riddles 
author: Ahmed Farahat


execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/ahmedfarhatx22/AFar_Structural_Engineering
  path_to_book: book
  branch: main

# GitHub Issues button and repository link
html:
  use_repository_button: true
  use_issues_button: true
